<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class PaisSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $path = Storage::path('archivos_desarrollador/paises.sql');
    DB::unprepared(file_get_contents($path));


    $codigoPaises = '[
      {"codigo": "AF", "nombre":"Afganistán"},
      {"codigo": "AX", "nombre":"Islas de Åland"},
      {"codigo": "AL", "nombre":"Albania"},
      {"codigo": "DZ", "nombre":"Algeria"},
      {"codigo": "AS", "nombre":"Samoa Americana"},
      {"codigo": "AD", "nombre":"Andorra"},
      {"codigo": "AO", "nombre":"Angola"},
      {"codigo": "AI", "nombre":"Anguila"},
      {"codigo": "AQ", "nombre":"Antártida"},
      {"codigo": "AG", "nombre":"Antigua y Barbuda"},
      {"codigo": "AR", "nombre":"Argentina"},
      {"codigo": "AM", "nombre":"Armenia"},
      {"codigo": "AW", "nombre":"Aruba"},
      {"codigo": "AU", "nombre":"Australia"},
      {"codigo": "AT", "nombre":"Austria"},
      {"codigo": "AZ", "nombre":"Azerbayán"},
      {"codigo": "BS", "nombre":"Bahamas"},
      {"codigo": "BH", "nombre":"Bahrein"},
      {"codigo": "BD", "nombre":"Bangladesh"},
      {"codigo": "BB", "nombre":"Barbados"},
      {"codigo": "BY", "nombre":"Bielorrusia"},
      {"codigo": "BE", "nombre":"Bélgica"},
      {"codigo": "BZ", "nombre":"Belice"},
      {"codigo": "BJ", "nombre":"Benín"},
      {"codigo": "BM", "nombre":"Islas Bermudas"},
      {"codigo": "BT", "nombre":"Bhután"},
      {"codigo": "BO", "nombre":"Bolivia"},
      {"codigo": "BA", "nombre":"Bosnia y Herzegovina"},
      {"codigo": "BW", "nombre":"Botsuana"},
      {"codigo": "BV", "nombre":"Isla Bouvet"},
      {"codigo": "BR", "nombre":"Brasil"},
      {"codigo": "IO", "nombre":"T. Británico del Océano Índico"},
      {"codigo": "BN", "nombre":"Brunéi"},
      {"codigo": "BG", "nombre":"Bulgaria"},
      {"codigo": "BF", "nombre":"Burkina Faso"},
      {"codigo": "BI", "nombre":"Burundi"},
      {"codigo": "KH", "nombre":"Camboya"},
      {"codigo": "CM", "nombre":"Camerún"},
      {"codigo": "CA", "nombre":"Canadá"},
      {"codigo": "CV", "nombre":"Cabo Verde"},
      {"codigo": "KY", "nombre":"Islas Caimán"},
      {"codigo": "CF", "nombre":"República Centroafricana"},
      {"codigo": "TD", "nombre":"Chad"},
      {"codigo": "CL", "nombre":"Chile"},
      {"codigo": "CN", "nombre":"China"},
      {"codigo": "CX", "nombre":"Isla de Navidad"},
      {"codigo": "CC", "nombre":"Islas Cocos (Keeling)"},
      {"codigo": "CO", "nombre":"Colombia"},
      {"codigo": "KM", "nombre":"Comoras"},
      {"codigo": "CG", "nombre":"República del Congo"},
      {"codigo": "CD", "nombre":"República democrática del Congo"},
      {"codigo": "CK", "nombre":"Islas Cook"},
      {"codigo": "CR", "nombre":"Costa Rica"},
      {"codigo": "CI", "nombre":"Costa de Marfil"},
      {"codigo": "HR", "nombre":"Croacia"},
      {"codigo": "CU", "nombre":"Cuba"},
      {"codigo": "CY", "nombre":"Chipre"},
      {"codigo": "CZ", "nombre":"República Checa"},
      {"codigo": "DK", "nombre":"Dinamarca"},
      {"codigo": "DJ", "nombre":"Yibuti"},
      {"codigo": "DM", "nombre":"Dominica"},
      {"codigo": "DO", "nombre":"República Dominicana"},
      {"codigo": "EC", "nombre":"Ecuador"},
      {"codigo": "EG", "nombre":"Egipto"},
      {"codigo": "SV", "nombre":"El Salvador"},
      {"codigo": "GQ", "nombre":"Guinea Ecuatorial"},
      {"codigo": "ER", "nombre":"Eritrea"},
      {"codigo": "EE", "nombre":"Estonia"},
      {"codigo": "ET", "nombre":"Etiopía"},
      {"codigo": "FK", "nombre":"Islas Malvinas"},
      {"codigo": "FO", "nombre":"Islas Feroe"},
      {"codigo": "FJ", "nombre":"Fiyi"},
      {"codigo": "FI", "nombre":"Finlandia"},
      {"codigo": "FR", "nombre":"Francia"},
      {"codigo": "GF", "nombre":"Guayana Francesa"},
      {"codigo": "PF", "nombre":"Polinesia Francesa"},
      {"codigo": "TF", "nombre":"T. Australes y Antárticas Franceses"},
      {"codigo": "GA", "nombre":"Gabón"},
      {"codigo": "GM", "nombre":"Gambia"},
      {"codigo": "GE", "nombre":"Georgia"},
      {"codigo": "DE", "nombre":"Alemania"},
      {"codigo": "GH", "nombre":"Ghana"},
      {"codigo": "GI", "nombre":"Gibraltar"},
      {"codigo": "GR", "nombre":"Grecia"},
      {"codigo": "GL", "nombre":"Groenlandia"},
      {"codigo": "GD", "nombre":"Granada"},
      {"codigo": "GP", "nombre":"Guadalupe"},
      {"codigo": "GU", "nombre":"Guam"},
      {"codigo": "GT", "nombre":"Guatemala"},
      {"codigo": "GG", "nombre":"Guernsey"},
      {"codigo": "GN", "nombre":"Guinea"},
      {"codigo": "GW", "nombre":"Guinea-Bissau"},
      {"codigo": "GY", "nombre":"Guyana"},
      {"codigo": "HT", "nombre":"Haití"},
      {"codigo": "HM", "nombre":"Islas Heard y McDonald"},
      {"codigo": "VA", "nombre":"Ciudad del Vaticano"},
      {"codigo": "HN", "nombre":"Honduras"},
      {"codigo": "HK", "nombre":"Hong kong"},
      {"codigo": "HU", "nombre":"Hungría"},
      {"codigo": "IS", "nombre":"Islandia"},
      {"codigo": "IN", "nombre":"India"},
      {"codigo": "ID", "nombre":"Indonesia"},
      {"codigo": "IR", "nombre":"Irán"},
      {"codigo": "IQ", "nombre":"Irak"},
      {"codigo": "IE", "nombre":"Irlanda"},
      {"codigo": "IM", "nombre":"Isla de Man"},
      {"codigo": "IL", "nombre":"Israel"},
      {"codigo": "IT", "nombre":"Italia"},
      {"codigo": "JM", "nombre":"Jamaica"},
      {"codigo": "JP", "nombre":"Japón"},
      {"codigo": "JE", "nombre":"Jersey"},
      {"codigo": "JO", "nombre":"Jordania"},
      {"codigo": "KZ", "nombre":"Kazajistán"},
      {"codigo": "KE", "nombre":"Kenia"},
      {"codigo": "KI", "nombre":"Kiribati"},
      {"codigo": "KR", "nombre":"Corea del Sur"},
      {"codigo": "KP", "nombre":"Corea del Norte"},
      {"codigo": "KW", "nombre":"Kuwait"},
      {"codigo": "KG", "nombre":"Kirgizstán"},
      {"codigo": "LA", "nombre":"Laos"},
      {"codigo": "LV", "nombre":"Letonia"},
      {"codigo": "LB", "nombre":"Líbano"},
      {"codigo": "LS", "nombre":"Lesoto"},
      {"codigo": "LR", "nombre":"Liberia"},
      {"codigo": "LY", "nombre":"Gran Yamahiriya Árabe Libia Popular Socialista"},
      {"codigo": "LI", "nombre":"Liechtenstein"},
      {"codigo": "LT", "nombre":"Lituania"},
      {"codigo": "LU", "nombre":"Luxemburgo"},
      {"codigo": "MO", "nombre":"Macao"},
      {"codigo": "MK", "nombre":"Macedônia"},
      {"codigo": "MG", "nombre":"Madagascar"},
      {"codigo": "MW", "nombre":"Malawi"},
      {"codigo": "MY", "nombre":"Malasia"},
      {"codigo": "MV", "nombre":"Islas Maldivas"},
      {"codigo": "ML", "nombre":"Mali"},
      {"codigo": "MT", "nombre":"Malta"},
      {"codigo": "MH", "nombre":"Islas Marshall"},
      {"codigo": "MQ", "nombre":"Martinica"},
      {"codigo": "MR", "nombre":"Mauritania"},
      {"codigo": "MU", "nombre":"Mauricio"},
      {"codigo": "YT", "nombre":"Mayotte"},
      {"codigo": "MX", "nombre":"México"},
      {"codigo": "FM", "nombre":"Micronesia"},
      {"codigo": "MD", "nombre":"Moldavia"},
      {"codigo": "MC", "nombre":"Mónaco"},
      {"codigo": "MN", "nombre":"Mongolia"},
      {"codigo": "ME", "nombre":"Montenegro"},
      {"codigo": "MS", "nombre":"Montserrat"},
      {"codigo": "MA", "nombre":"Marruecos"},
      {"codigo": "MZ", "nombre":"Mozambique"},
      {"codigo": "MM", "nombre":"Birmania"},
      {"codigo": "NA", "nombre":"Namibia"},
      {"codigo": "NR", "nombre":"Nauru"},
      {"codigo": "NP", "nombre":"Nepal"},
      {"codigo": "NL", "nombre":"Países Bajos"},
      {"codigo": "AN", "nombre":"Antillas Neerlandesas"},
      {"codigo": "NC", "nombre":"Nueva Caledonia"},
      {"codigo": "NZ", "nombre":"Nueva Zelanda"},
      {"codigo": "NI", "nombre":"Nicaragua"},
      {"codigo": "NE", "nombre":"Níger"},
      {"codigo": "NG", "nombre":"Nigeria"},
      {"codigo": "NU", "nombre":"Niue"},
      {"codigo": "NF", "nombre":"Isla Norfolk"},
      {"codigo": "MP", "nombre":"Islas Marianas del Norte"},
      {"codigo": "NO", "nombre":"Noruega"},
      {"codigo": "OM", "nombre":"Omán"},
      {"codigo": "PK", "nombre":"Pakistán"},
      {"codigo": "PW", "nombre":"Palau"},
      {"codigo": "PS", "nombre":"Palestina"},
      {"codigo": "PA", "nombre":"Panamá"},
      {"codigo": "PG", "nombre":"Papúa Nueva Guinea"},
      {"codigo": "PY", "nombre":"Paraguay"},
      {"codigo": "PE", "nombre":"Perú"},
      {"codigo": "PH", "nombre":"Filipinas"},
      {"codigo": "PN", "nombre":"Islas Pitcairn"},
      {"codigo": "PL", "nombre":"Polonia"},
      {"codigo": "PT", "nombre":"Portugal"},
      {"codigo": "PR", "nombre":"Puerto Rico"},
      {"codigo": "QA", "nombre":"Qatar"},
      {"codigo": "RE", "nombre":"Isla Reunión"},
      {"codigo": "RO", "nombre":"Rumanía"},
      {"codigo": "RU", "nombre":"Rusia"},
      {"codigo": "RW", "nombre":"Ruanda"},
      {"codigo": "BL", "nombre":"San Bartolomé"},
      {"codigo": "SH", "nombre":"Santa Elena"},
      {"codigo": "KN", "nombre":"San Cristóbal y Nieves"},
      {"codigo": "LC", "nombre":"Santa Lucía"},
      {"codigo": "MF", "nombre":"San Martín (Francia)"},
      {"codigo": "PM", "nombre":"San Pedro y Miquelón"},
      {"codigo": "VC", "nombre":"San Vicente y las Granadinas"},
      {"codigo": "WS", "nombre":"Samoa"},
      {"codigo": "SM", "nombre":"San Marino"},
      {"codigo": "ST", "nombre":"Santo Tomé y Príncipe"},
      {"codigo": "SA", "nombre":"Arabia Saudita"},
      {"codigo": "SN", "nombre":"Senegal"},
      {"codigo": "RS", "nombre":"Serbia"},
      {"codigo": "SC", "nombre":"Seychelles"},
      {"codigo": "SL", "nombre":"Sierra Leona"},
      {"codigo": "SG", "nombre":"Singapur"},
      {"codigo": "SK", "nombre":"Eslovaquia"},
      {"codigo": "SI", "nombre":"Eslovenia"},
      {"codigo": "SB", "nombre":"Islas Salomón"},
      {"codigo": "SO", "nombre":"Somalia"},
      {"codigo": "ZA", "nombre":"Sudáfrica"},
      {"codigo": "GS", "nombre":"Georgia del Sur"},
      {"codigo": "ES", "nombre":"España"},
      {"codigo": "LK", "nombre":"Sri lanka"},
      {"codigo": "SD", "nombre":"Sudán"},
      {"codigo": "SR", "nombre":"Surinám"},
      {"codigo": "SJ", "nombre":"Svalbard y Jan Mayen"},
      {"codigo": "SZ", "nombre":"Swazilandia"},
      {"codigo": "SE", "nombre":"Suecia"},
      {"codigo": "CH", "nombre":"Suiza"},
      {"codigo": "SY", "nombre":"Siria"},
      {"codigo": "TW", "nombre":"Taiwán"},
      {"codigo": "TJ", "nombre":"Tadjikistán"},
      {"codigo": "TZ", "nombre":"Tanzania"},
      {"codigo": "TH", "nombre":"Tailandia"},
      {"codigo": "TL", "nombre":"Timor Oriental"},
      {"codigo": "TG", "nombre":"Togo"},
      {"codigo": "TK", "nombre":"Tokelau"},
      {"codigo": "TO", "nombre":"Tonga"},
      {"codigo": "TT", "nombre":"Trinidad y Tobago"},
      {"codigo": "TN", "nombre":"Tunez"},
      {"codigo": "TR", "nombre":"Turquía"},
      {"codigo": "TM", "nombre":"Turkmenistán"},
      {"codigo": "TC", "nombre":"Islas Turcas y Caicos"},
      {"codigo": "TV", "nombre":"Tuvalu"},
      {"codigo": "UG", "nombre":"Uganda"},
      {"codigo": "UA", "nombre":"Ucrania"},
      {"codigo": "AE", "nombre":"Emiratos Árabes Unidos"},
      {"codigo": "GB", "nombre":"Reino Unido"},
      {"codigo": "US", "nombre":"Estados Unidos de América"},
      {"codigo": "UM", "nombre":"Islas Ultramarinas de EEUU"},
      {"codigo": "UY", "nombre":"Uruguay"},
      {"codigo": "UZ", "nombre":"Uzbekistán"},
      {"codigo": "VU", "nombre":"Vanuatu"},
      {"codigo": "VE", "nombre":"Venezuela"},
      {"codigo": "VN", "nombre":"Vietnam"},
      {"codigo": "VG", "nombre":"Islas Vírgenes Británicas"},
      {"codigo": "VI", "nombre":"Islas Vírgenes de los EEUU"},
      {"codigo": "WF", "nombre":"Wallis y Futuna"},
      {"codigo": "EH", "nombre":"Sahara Occidental"},
      {"codigo": "YE", "nombre":"Yemen"},
      {"codigo": "ZM", "nombre":"Zambia"},
      {"codigo": "ZW", "nombre":"Zimbabue"}
   ]';

   $codigoPaises = collect(json_decode($codigoPaises));

   $paises = Pais::get();
   foreach($paises as $pais)
   {
     $filtro = $codigoPaises->filter(function ($item) use ($pais) {
       return strpos($item->nombre, $pais->nombre) !== false;
     });

     if($filtro->first())
     {
       $pais->codigo_alpha = $filtro->first()->codigo;
       $pais->save();
     }
   }
  }
}
