<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Profesion;

class ProfesionSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $profesiones = '[
      {"id":"1","nombre":"Abogado"},
      {"id":"2","nombre":"Académico"},
      {"id":"3","nombre":"Adjunto"},
      {"id":"4","nombre":"Administrador"},
      {"id":"5","nombre":"Administrativo"},
      {"id":"6","nombre":"Agrónomo"},
      {"id":"7","nombre":"Alergólogo"},
      {"id":"8","nombre":"Alergóloga"},
      {"id":"9","nombre":"Almacenero"},
      {"id":"10","nombre":"Almacenera"},
      {"id":"11","nombre":"Anatomista"},
      {"id":"12","nombre":"Anestesiólogo"},
      {"id":"13","nombre":"Anestesióloga"},
      {"id":"14","nombre":"Antologista"},
      {"id":"15","nombre":"Antropólogo"},
      {"id":"16","nombre":"Arabista"},
      {"id":"17","nombre":"Archivero"},
      {"id":"18","nombre":"Arqueólogo"},
      {"id":"19","nombre":"Arquitecto"},
      {"id":"20","nombre":"Asesor"},
      {"id":"21","nombre":"Asistente"},
      {"id":"22","nombre":"Astrofísico"},
      {"id":"23","nombre":"Astrólogo"},
      {"id":"24","nombre":"Astrónomo"},
      {"id":"25","nombre":"Atleta"},
      {"id":"26","nombre":"ATS"},
      {"id":"27","nombre":"Autor"},
      {"id":"28","nombre":"Avicultor"},
      {"id":"29","nombre":"Bacteriólogo"},
      {"id":"30","nombre":"Bedel"},
      {"id":"31","nombre":"Bibliógrafo"},
      {"id":"32","nombre":"Bibliotecario"},
      {"id":"33","nombre":"Biofísico"},
      {"id":"34","nombre":"Biógrafo"},
      {"id":"35","nombre":"Biólogo"},
      {"id":"36","nombre":"Bioquímico"},
      {"id":"37","nombre":"Botánico"},
      {"id":"38","nombre":"Cancerólogo"},
      {"id":"39","nombre":"Cardiólogo"},
      {"id":"40","nombre":"Cartógrafo"},
      {"id":"41","nombre":"Castrador"},
      {"id":"42","nombre":"Catedrático"},
      {"id":"43","nombre":"Cirujano"},
      {"id":"44","nombre":"Citólogo"},
      {"id":"45","nombre":"Climatólogo"},
      {"id":"46","nombre":"Codirector"},
      {"id":"47","nombre":"Comadrón"},
      {"id":"48","nombre":"Consejero"},
      {"id":"49","nombre":"Conservador"},
      {"id":"50","nombre":"Conserje"},
      {"id":"51","nombre":"Coordinador"},
      {"id":"52","nombre":"Cosmógrafo"},
      {"id":"53","nombre":"Cosmólogo"},
      {"id":"54","nombre":"Criminalista"},
      {"id":"55","nombre":"Cronólogo"},
      {"id":"56","nombre":"Decano"},
      {"id":"57","nombre":"Decorador"},
      {"id":"58","nombre":"Defensor"},
      {"id":"59","nombre":"Delegado"},
      {"id":"60","nombre":"Delineante"},
      {"id":"61","nombre":"Demógrafo"},
      {"id":"62","nombre":"Dentista"},
      {"id":"63","nombre":"Dermatólogo"},
      {"id":"64","nombre":"Dibujante"},
      {"id":"65","nombre":"Directivo"},
      {"id":"66","nombre":"Director"},
      {"id":"67","nombre":"Dirigente"},
      {"id":"68","nombre":"Doctor"},
      {"id":"69","nombre":"Documentalista"},
      {"id":"70","nombre":"Ecólogo"},
      {"id":"71","nombre":"Economista"},
      {"id":"72","nombre":"Educador"},
      {"id":"73","nombre":"Egiptólogo"},
      {"id":"74","nombre":"Endocrinólogo"},
      {"id":"75","nombre":"Enfermero"},
      {"id":"76","nombre":"Enólogo"},
      {"id":"77","nombre":"Entomólogo"},
      {"id":"78","nombre":"Epidemiólogo"},
      {"id":"79","nombre":"Especialista"},
      {"id":"80","nombre":"Espeleólogo"},
      {"id":"81","nombre":"Estadista"},
      {"id":"82","nombre":"Estadístico"},
      {"id":"83","nombre":"Etimólogo"},
      {"id":"84","nombre":"Etnógrafo"},
      {"id":"85","nombre":"Etnólogo"},
      {"id":"86","nombre":"Etólogo"},
      {"id":"87","nombre":"Examinador"},
      {"id":"88","nombre":"Facultativo"},
      {"id":"89","nombre":"Farmacéutico"},
      {"id":"90","nombre":"Farmacólogo"},
      {"id":"91","nombre":"Filólogo"},
      {"id":"92","nombre":"Filósofo"},
      {"id":"93","nombre":"Fiscal"},
      {"id":"94","nombre":"Físico"},
      {"id":"95","nombre":"Fisiólogo"},
      {"id":"96","nombre":"Fisioterapeuta"},
      {"id":"97","nombre":"Fonetista"},
      {"id":"98","nombre":"Foníatra"},
      {"id":"99","nombre":"Fonólogo"},
      {"id":"100","nombre":"Forense"},
      {"id":"101","nombre":"Fotógrafo"},
      {"id":"102","nombre":"Funcionario"},
      {"id":"103","nombre":"Gemólogo"},
      {"id":"104","nombre":"Genetista"},
      {"id":"105","nombre":"Geobotánica"},
      {"id":"106","nombre":"Geodesta"},
      {"id":"107","nombre":"Geofísico"},
      {"id":"108","nombre":"Geógrafo"},
      {"id":"109","nombre":"Geólogo"},
      {"id":"110","nombre":"Geomántico"},
      {"id":"111","nombre":"Geómetra"},
      {"id":"112","nombre":"Geoquímica"},
      {"id":"113","nombre":"Gerente"},
      {"id":"114","nombre":"Geriatra"},
      {"id":"115","nombre":"Gerontólogo"},
      {"id":"116","nombre":"Gestor"},
      {"id":"117","nombre":"Grabador"},
      {"id":"118","nombre":"Graduado social"},
      {"id":"119","nombre":"Grafólogo"},
      {"id":"120","nombre":"Gramático"},
      {"id":"121","nombre":"Hematólogo"},
      {"id":"122","nombre":"Hepatólogo"},
      {"id":"123","nombre":"Hidrogeólogo"},
      {"id":"124","nombre":"Hidrógrafo"},
      {"id":"125","nombre":"Hidrólogo"},
      {"id":"126","nombre":"Higienista"},
      {"id":"127","nombre":"Hispanista"},
      {"id":"128","nombre":"Historiador"},
      {"id":"129","nombre":"Homeópata"},
      {"id":"130","nombre":"Informático"},
      {"id":"131","nombre":"Ingeniero"},
      {"id":"132","nombre":"Inmunólogo"},
      {"id":"133","nombre":"Inspector"},
      {"id":"134","nombre":"Interino"},
      {"id":"135","nombre":"Interventor"},
      {"id":"136","nombre":"Investigado"},
      {"id":"137","nombre":"Jardinero"},
      {"id":"138","nombre":"Jefe"},
      {"id":"139","nombre":"Juez"},
      {"id":"140","nombre":"Latinista"},
      {"id":"141","nombre":"Lector"},
      {"id":"142","nombre":"Letrado (abogado)"},
      {"id":"143","nombre":"Lexicógrafo"},
      {"id":"144","nombre":"Lexicólogo"},
      {"id":"145","nombre":"Licenciado"},
      {"id":"146","nombre":"Lingüista"},
      {"id":"147","nombre":"Logopeda"},
      {"id":"148","nombre":"Maestro"},
      {"id":"149","nombre":"Matemático"},
      {"id":"150","nombre":"Matrón"},
      {"id":"151","nombre":"Medico"},
      {"id":"152","nombre":"Meteorólogo"},
      {"id":"153","nombre":"Micólogo"},
      {"id":"154","nombre":"Microbiológico"},
      {"id":"155","nombre":"Microcirujano"},
      {"id":"156","nombre":"Mimógrafo"},
      {"id":"157","nombre":"Mineralogista"},
      {"id":"158","nombre":"Monitor"},
      {"id":"159","nombre":"Musicólogo"},
      {"id":"160","nombre":"Naturópata"},
      {"id":"161","nombre":"Nefrólogo"},
      {"id":"162","nombre":"Neumólogo"},
      {"id":"163","nombre":"Neuroanatomista"},
      {"id":"164","nombre":"Neurobiólogo"},
      {"id":"165","nombre":"Neurocirujano"},
      {"id":"166","nombre":"Neuroembriólogo"},
      {"id":"167","nombre":"Neurofisiólogo"},
      {"id":"168","nombre":"Neurólogo"},
      {"id":"169","nombre":"Nutrólogo"},
      {"id":"170","nombre":"Oceanógrafo"},
      {"id":"171","nombre":"Odontólogo"},
      {"id":"172","nombre":"Oficial"},
      {"id":"173","nombre":"Oficinista"},
      {"id":"174","nombre":"Oftalmólogo"},
      {"id":"175","nombre":"Oncólogo"},
      {"id":"176","nombre":"Óptico"},
      {"id":"177","nombre":"Optometrista"},
      {"id":"178","nombre":"Ordenanza"},
      {"id":"179","nombre":"Orientador"},
      {"id":"180","nombre":"Ornitólogo"},
      {"id":"181","nombre":"Ortopédico"},
      {"id":"182","nombre":"Ortopedista"},
      {"id":"183","nombre":"Osteólogo"},
      {"id":"184","nombre":"Osteópata"},
      {"id":"185","nombre":"Otorrinolaringólogo"},
      {"id":"186","nombre":"Paleobiólogo"},
      {"id":"187","nombre":"Paleobotánico"},
      {"id":"188","nombre":"Paleógrafo"},
      {"id":"189","nombre":"Paleólogo"},
      {"id":"190","nombre":"Paleontólogo"},
      {"id":"191","nombre":"Pastor"},
      {"id":"192","nombre":"Patólogo"},
      {"id":"193","nombre":"Pedagogo"},
      {"id":"194","nombre":"Pediatra"},
      {"id":"195","nombre":"Pedicuro"},
      {"id":"196","nombre":"Periodista"},
      {"id":"197","nombre":"Perito"},
      {"id":"198","nombre":"Piscicultor"},
      {"id":"199","nombre":"Podólogo"},
      {"id":"200","nombre":"Portero"},
      {"id":"201","nombre":"Prehistoriador"},
      {"id":"202","nombre":"Presidente"},
      {"id":"203","nombre":"Proctólogo"},
      {"id":"204","nombre":"Profesor"},
      {"id":"205","nombre":"Programador"},
      {"id":"206","nombre":"Protésico"},
      {"id":"207","nombre":"Protésica"},
      {"id":"208","nombre":"Proveedor"},
      {"id":"209","nombre":"Psicoanalista"},
      {"id":"210","nombre":"Psicólogo"},
      {"id":"211","nombre":"Psicofísico"},
      {"id":"212","nombre":"Psicopedagogo"},
      {"id":"213","nombre":"Psicoterapeuta"},
      {"id":"214","nombre":"Psiquiatra"},
      {"id":"215","nombre":"Publicista"},
      {"id":"216","nombre":"Publicitario"},
      {"id":"217","nombre":"Puericultor"},
      {"id":"218","nombre":"Químico"},
      {"id":"219","nombre":"Quiropráctico"},
      {"id":"220","nombre":"Radioastrónomo"},
      {"id":"221","nombre":"Radiofonista"},
      {"id":"222","nombre":"Radiólogo"},
      {"id":"223","nombre":"Radiotécnico"},
      {"id":"224","nombre":"Radiotelefonista"},
      {"id":"225","nombre":"Radiotelegrafista"},
      {"id":"226","nombre":"Radioterapeuta"},
      {"id":"227","nombre":"Rector"},
      {"id":"228","nombre":"Sanitario"},
      {"id":"229","nombre":"Secretario"},
      {"id":"230","nombre":"Sexólogo"},
      {"id":"231","nombre":"Sismólogo"},
      {"id":"232","nombre":"Sociólogo"},
      {"id":"233","nombre":"Subdelegado"},
      {"id":"234","nombre":"Subdirector"},
      {"id":"235","nombre":"Subsecretario"},
      {"id":"236","nombre":"Telefonista"},
      {"id":"237","nombre":"Teólogo"},
      {"id":"238","nombre":"Terapeuta"},
      {"id":"239","nombre":"Tocoginecólogo"},
      {"id":"240","nombre":"Tocólogo"},
      {"id":"241","nombre":"Toxicólogo"},
      {"id":"242","nombre":"Traductor"},
      {"id":"243","nombre":"Transcriptor"},
      {"id":"244","nombre":"Traumatólogo"},
      {"id":"245","nombre":"Tutor"},
      {"id":"246","nombre":"Urólogo"},
      {"id":"247","nombre":"Veterinario"},
      {"id":"248","nombre":"Vicedecano"},
      {"id":"249","nombre":"Vicedirector"},
      {"id":"250","nombre":"Vicegerente"},
      {"id":"251","nombre":"Vicepresidente"},
      {"id":"252","nombre":"Vicerrector"},
      {"id":"253","nombre":"Vicesecretario"},
      {"id":"254","nombre":"Virólogo"},
      {"id":"255","nombre":"Viticultor"},
      {"id":"256","nombre":"Vulcanólogo"},
      {"id":"257","nombre":"Xilógrafo"},
      {"id":"258","nombre":"Zoólogo"},
      {"id":"259","nombre":"Zootécnico"},
      {"id":"260","nombre":"Ingeniería militar"},
      {"id":"261","nombre":"Ingeniería en armamento"},
      {"id":"262","nombre":"Ingeniería en maquinarias de asedio"},
      {"id":"263","nombre":"Ingeniería en politécnica militar"},
      {"id":"264","nombre":"Ingeniería balística"},
      {"id":"265","nombre":"Ingeniería naval"},
      {"id":"266","nombre":"Ingeniería aeronáutica"},
      {"id":"267","nombre":"Ingeniería automotriz"},
      {"id":"268","nombre":"Ingeniería marítima"},
      {"id":"269","nombre":"Ingeniería civil"},
      {"id":"270","nombre":"Ingeniería sanitaria"},
      {"id":"271","nombre":"Relaciones Internacionales"},
      {"id":"272","nombre":"Ingeniería estructural"},
      {"id":"273","nombre":"Ingeniería hidráulica"},
      {"id":"274","nombre":"Ingeniería de minas"},
      {"id":"275","nombre":"Ingeniería geológica"},
      {"id":"276","nombre":"Ingeniería del petróleo"},
      {"id":"277","nombre":"Ingeniería del transporte"},
      {"id":"278","nombre":"Ingeniería topográfica"},
      {"id":"279","nombre":"Ingeniería agrícola"},
      {"id":"280","nombre":"Ingeniería de montes y forestal"},
      {"id":"281","nombre":"Ingeniería pesquera"},
      {"id":"282","nombre":"Ingeniería metalúrgica"},
      {"id":"283","nombre":"Ingeniería mecánica"},
      {"id":"284","nombre":"Ingeniería electromecánica"},
      {"id":"285","nombre":"Ingeniería en climatización"},
      {"id":"286","nombre":"Ingeniería en refrigeración"},
      {"id":"287","nombre":"Ingeniería naval"},
      {"id":"288","nombre":"Ingeniería aeroespacial"},
      {"id":"289","nombre":"Ingeniería aeronáutica"},
      {"id":"290","nombre":"Ingeniería automotriz"},
      {"id":"291","nombre":"Ingeniería acústica"},
      {"id":"292","nombre":"Mecánica"},
      {"id":"293","nombre":"Ingeniería nanotecnológica"},
      {"id":"294","nombre":"Ingeniería mecánica de fluidos"},
      {"id":"295","nombre":"Ingeniería en mantenimiento mecánico"},
      {"id":"296","nombre":"Ingeniería eléctrica"},
      {"id":"297","nombre":"Instrumentador quirúrgico"},
      {"id":"298","nombre":"Ingeniería electrónica"},
      {"id":"299","nombre":"Ingeniería de telecomunicaciones"},
      {"id":"300","nombre":"Ingeniería de control"},
      {"id":"301","nombre":"Ingeniería física"},
      {"id":"302","nombre":"Ingeniería biónica"},
      {"id":"303","nombre":"Ingeniería de la energía"},
      {"id":"304","nombre":"Ingeniería espacial"},
      {"id":"305","nombre":"Ingeniería informática"},
      {"id":"306","nombre":"Ingeniería de sistemas de información"},
      {"id":"307","nombre":"Ingeniería en computación"},
      {"id":"308","nombre":"Ingeniería geofísica"},
      {"id":"309","nombre":"Ingeniería geológica"},
      {"id":"310","nombre":"Ingeniería en multimedia"},
      {"id":"311","nombre":"Ingeniería en automatización y control industrial"},
      {"id":"312","nombre":"Música"},
      {"id":"313","nombre":"Ingeniería de control"},
      {"id":"314","nombre":"Ingeniería mecatrónica"},
      {"id":"315","nombre":"Ingeniería química"},
      {"id":"316","nombre":"Ingeniería de materiales"},
      {"id":"317","nombre":"Ingeniería petroquímica"},
      {"id":"318","nombre":"Ingeniería de alimentos"},
      {"id":"319","nombre":"Ingeniería agrícola"},
      {"id":"320","nombre":"Ingeniería agroindustrial"},
      {"id":"321","nombre":"Ingeniería de alimentos"},
      {"id":"322","nombre":"Ingeniería biológica"},
      {"id":"323","nombre":"Ingeniería biomédica"},
      {"id":"324","nombre":"Ingeniería bioquímica"},
      {"id":"325","nombre":"Ingeniería genética"},
      {"id":"326","nombre":"Ingeniería agroforestal"},
      {"id":"327","nombre":"Ingeniería de montes"},
      {"id":"328","nombre":"Ingeniería técnica forestal"},
      {"id":"329","nombre":"Ingeniería agrícola"},
      {"id":"330","nombre":"Ingeniería de la producción en agroecosistemas"},
      {"id":"331","nombre":"Ingeniería ambiental"},
      {"id":"332","nombre":"Ingeniería industrial"},
      {"id":"333","nombre":"Ingeniería en mantenimiento industrial"},
      {"id":"334","nombre":"Ingeniería financiera"},
      {"id":"335","nombre":"Ingeniería logística"},
      {"id":"336","nombre":"Ingeniería administrativa"},
      {"id":"337","nombre":"Ingeniería de producto"},
      {"id":"338","nombre":"Ingeniería de producción"},
      {"id":"339","nombre":"Ingeniería de la energía"},
      {"id":"340","nombre":"Ingeniería de sonido"},
      {"id":"341","nombre":"Ingeniería de negocios"},
      {"id":"342","nombre":"Ingeniería comercial"},
      {"id":"343","nombre":"Ingeniería en diseño industrial"},
      {"id":"344","nombre":"Ingeniería de seguridad"},
      {"id":"345","nombre":"Ingeniería Empresarial"},
      {"id":"346","nombre":"Vendedor"},
      {"id":"347","nombre":"Ingeniería informática"},
      {"id":"348","nombre":"Ingeniería de proyectos"},
      {"id":"349","nombre":"Ingeniería de sistemas empresariales"},
      {"id":"350","nombre":"Ingeniería administrativa"},
      {"id":"351","nombre":"Ingeniería económica"},
      {"id":"352","nombre":"Ingeniería financiera"},
      {"id":"353","nombre":"Ingeniería de procesos"},
      {"id":"354","nombre":"ingeniería de producción"},
      {"id":"355","nombre":"Ingeniería de seguridad"},
      {"id":"356","nombre":"Ingeniería nuclear"},
      {"id":"357","nombre":"Ingeniería de calidad"},
      {"id":"358","nombre":"Ingeniería física"},
      {"id":"359","nombre":"Ingeniería geofísica"},
      {"id":"360","nombre":"Ingeniería geológica"},
      {"id":"361","nombre":"Ingeniería espacial"},
      {"id":"362","nombre":"Soldado"},
      {"id":"363","nombre":"Enfermería"},
      {"id":"364","nombre":"Diseño gráfico"},
      {"id":"365","nombre":"Suboficial"},
      {"id":"366","nombre":"Contador"},
      {"id":"367","nombre":"Analista"},
      {"id":"368","nombre":"Filología"},
      {"id":"369","nombre":"Comunicación"},
      {"id":"370","nombre":"Presentador"},
      {"id":"371","nombre":"Electricista"},
      {"id":"372","nombre":"Producción audiovisual"},
      {"id":"373","nombre":"Diseño textil"},
      {"id":"374","nombre":"Confecciones"},
      {"id":"375","nombre":"Estilista"},
      {"id":"376","nombre":"Diseñador de modas"},
      {"id":"377","nombre":"Revisor fiscal"},
      {"id":"378","nombre":"Comunicación social"},
      {"id":"379","nombre":"Diseño de Joyas"},
      {"id":"380","nombre":"Archivística"},
      {"id":"381","nombre":"Conductor"},
      {"id":"382","nombre":"Construcción"},
      {"id":"383","nombre":"Chef"},
      {"id":"384","nombre":"Entrenador deportivo"},
      {"id":"385","nombre":"Instructor de conducción"},
      {"id":"386","nombre":"Latonería"},
      {"id":"387","nombre":"Educación física"},
      {"id":"388","nombre":"Relaciones públicas"},
      {"id":"389","nombre":"Comercio exterior"},
      {"id":"390","nombre":"Aduana"},
      {"id":"391","nombre":"Aduanas y comercio exterior"},
      {"id":"392","nombre":"Licenciatura en educación inicial"},
      {"id":"393","nombre":"Licenciatura en educación preescolar"},
      {"id":"394","nombre":"Ministro"},
      {"id":"395","nombre":"Evangelista"},
      {"id":"396","nombre":"Magisterio"},
      {"id":"397","nombre":"Actor"},
      {"id":"398","nombre":"Humorista"},
      {"id":"399","nombre":"Policia"},
      {"id":"400","nombre":"Panadero"},
      {"id":"401","nombre":"Salud ocupacional"},
      {"id":"402","nombre":"Soldado profesional"},
      {"id":"403","nombre":"Mercadología"},
      {"id":"404","nombre":"Mercadotecnia"},
      {"id":"405","nombre":"Marketing"},
      {"id":"406","nombre":"Ventas"},
      {"id":"407","nombre":"Talento humano"},
      {"id":"408","nombre":"Lenguas modernas"},
      {"id":"409","nombre":"Diseñador industrial"},
      {"id":"410","nombre":"Fonoaudiólogo"},
      {"id":"411","nombre":"Apóstol"},
      {"id":"412","nombre":"Profeta"},
      {"id":"413","nombre":"Lenguas extranjeras"},
      {"id":"414","nombre":"Negocios internacionales"},
      {"id":"415","nombre":"Culinaria"},
      {"id":"416","nombre":"Literatura"},
      {"id":"417","nombre":"Esteticista"},
      {"id":"418","nombre":"Etnobiología"},
      {"id":"419","nombre":"Cosmetología"},
      {"id":"420","nombre":"Educación parvularia"},
      {"id":"421","nombre":"Profesional en seguridad y salud en el trabajo"},
      {"id":"422","nombre":"Carpintería"},
      {"id":"423","nombre":"Guía de turismo"},
      {"id":"424","nombre":"Ingeniería electrónica industrial"},
      {"id":"425","nombre":"Trabajo social"},
      {"id":"426","nombre":"Arte - Danza"},
      {"id":"427","nombre":"Domiciliario"},
      {"id":"428","nombre":"Modistería"},
      {"id":"429","nombre":"Campesino"},
      {"id":"430","nombre":"Educación especial"},
      {"id":"431","nombre":"Salvavidas"},
      {"id":"432","nombre":"Mentor"},
      {"id":"433","nombre":"Camarero"}
    ]';

    $items = json_decode($profesiones);

    foreach ($items as $item) {
      Profesion::create([
        'nombre' => $item->nombre,
      ]);
    }
  }
}
